#!/usr/bin/env python3
"""Patch the CI-generated android/app/build.gradle[.kts] for core library desugaring.

flutter_local_notifications (>=17) uses java.time APIs and fails the release build
with "requires core library desugaring to be enabled" unless the app module opts in.
android/ is generated by `flutter create` in CI and not committed, so the opt-in is
applied here instead of being checked in.

Deliberately non-fatal: if the generated gradle file does not match what we expect,
this prints why and exits 0 so the real gradle error surfaces in the build step.
"""

import os
import re
import sys

CANDIDATES = ("android/app/build.gradle.kts", "android/app/build.gradle")
DESUGAR_VERSION = "2.1.4"


def main() -> int:
    path = next((p for p in CANDIDATES if os.path.exists(p)), None)
    if path is None:
        print("patch_gradle: no android/app/build.gradle[.kts]; skipping")
        return 0

    kts = path.endswith(".kts")
    src = open(path, encoding="utf-8").read()

    if "coreLibraryDesugaring" in src:
        print(f"patch_gradle: {path} already enables desugaring; skipping")
        return 0

    flag = (
        "isCoreLibraryDesugaringEnabled = true"
        if kts
        else "coreLibraryDesugaringEnabled true"
    )
    patched, n = re.subn(
        r"compileOptions\s*\{",
        lambda m: m.group(0) + "\n        " + flag,
        src,
        count=1,
    )
    if n == 0:
        print(f"patch_gradle: no compileOptions block in {path}; skipping")
        return 0

    dep = (
        f'    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:{DESUGAR_VERSION}")'
        if kts
        else f'    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VERSION}"'
    )
    patched = patched.rstrip() + "\n\ndependencies {\n" + dep + "\n}\n"

    open(path, "w", encoding="utf-8").write(patched)
    print(f"patch_gradle: patched {path}\n---\n{patched}---")
    return 0


if __name__ == "__main__":
    sys.exit(main())
